### ISSUE TITLE
RuntimeError: Parameter at index 988 with name img_backbone.levels.3.blocks.3.gamma2 has been marked as ready twice.

### ISSUE THREAD

**Issue by OrangeSodahub** [OpenGVLab/InternImage#125] opened 2023-04-22 13:46 UTC
Thanks for your work.

When I replace the image backone `resnet101` with your `internimage-s`, and I modified the channels in FPN to satisfy the backbone. I occurred this runtime error:

`Parameter at index 988 with name img_backbone.levels.3.blocks.3.gamma2 has been marked as ready twice. This means that multiple autograd engine  hooks have fired for this particular parameter during this iteration.`,

I wonder if you ever occurred this? Could you give some advice? This looks like a time-consuming debug.

**Comment by 116022017144** [comment] 2023-05-05 09:34
Do you solve it?I also meet this problem.
RuntimeError: Expected to mark a variable ready only once. This error is caused by one of the following reasons: 1) Use of a module parameter outside the `forward` function. Please make sure model parameters are not shared across multiple concurrent forward-backward passes. or try to use _set_static_graph() as a workaround if this module graph does not change during training loop.2) Reused parameters in multiple reentrant backward passes. For example, if you use multiple `checkpoint` functions to wrap the same part of your model, it would result in the same set of parameters been used by different reentrant backward passes multiple times, and hence marking a variable ready multiple times. DDP does not support such use cases in default. You can try to use _set_static_graph() as a workaround if your module graph does not change over iterations.
Parameter at index 635 has been marked as ready twice. This means that multiple autograd engine  hooks have fired for this particular parameter during this iteration. You can set the environment variable TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print parameter names for further debugging.
![image](https://user-images.githubusercontent.com/33896598/236424176-5412f43c-05ee-4584-9e92-f8aa05832205.png)

**Comment by OrangeSodahub** [comment] 2023-05-15 13:26
No, have you solved?

**Comment by OrangeSodahub** [comment] 2023-05-22 15:31
Solved.

**Closed** 2023-05-22 15:31 UTC

**Comment by promesse** [comment] 2023-05-25 06:08
> Solved.

How to solve it
Thanks for your reply
